---
# Objects are defined here:
# https://kubernetes.io/docs/concepts/policy/pod-security-policy

kind: PodSecurityPolicy
apiVersion: extensions/v1beta1
metadata:
  name: production
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
    - "*"
